qtbase_%.bbappend: Remove vulkan in LDP [LF-9706]
imx-image-dsktop would not build qt lib into image.
but to generate meta-toolchain-qt6 sdk, qtbase depends vulkan,
vulkan driver libvulkan1.so have two rpm packages path,which cause install issue, error show as:
Error: Transaction test error:
  file /usr/lib/libvulkan.so conflicts between attempted installs of libvulkan1-1.2.182.0-r0.armv8a_mx8m and libvulkan-imx-1:6.4.11.p1.2.1d+aarch64-r0.armv8a_mx8m
  file /usr/lib/libvulkan.so.1 conflicts between attempted installs of libvulkan1-1.2.182.0-r0.armv8a_mx8m and libvulkan-imx-1:6.4.11.p1.2.1d+aarch64-r0.armv8a_mx8m

Signed-off-by: Zelan Zou <zelan.zou@nxp.com>